_wandb:
    value:
        cli_version: 0.21.0
        m: []
        python_version: 3.10.9
        t:
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.9
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
leverage:
    value: 75
margin_per_trade:
    value: 5
max_positions_per_symbol:
    value: 1
max_total_positions:
    value: 2
min_balance:
    value: 20
momentum_threshold:
    value: 0.001
rsi_lower:
    value: 25
rsi_upper:
    value: 75
stop_loss_pct:
    value: 0.0133
take_profit_pct:
    value: 0.03
volume_multiplier:
    value: 1.2
