wandb_version: 1

chunk_size:
  value: 50
chunking_method:
  value: rows
leverage:
  value: 10
position_size_pct:
  value: 0.2272216815806592
stop_loss_pct:
  value: 0.01400021089956217
take_profit_pct:
  value: 0.027651870937775415
time_window_idx:
  value: 4
