wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: rows
leverage:
  value: 5
position_size_pct:
  value: 0.05589392280715069
stop_loss_pct:
  value: 0.022181315492968583
take_profit_pct:
  value: 0.07382197377770419
time_window_idx:
  value: 5
