wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: time
leverage:
  value: 20
position_size_pct:
  value: 0.1784653932813977
stop_loss_pct:
  value: 0.008806124527992308
take_profit_pct:
  value: 0.019103256855513635
time_window_idx:
  value: 4
