wandb_version: 1

chunk_size:
  value: 200
chunking_method:
  value: rows
leverage:
  value: 20
position_size_pct:
  value: 0.21509457770522705
stop_loss_pct:
  value: 0.008666853813828361
take_profit_pct:
  value: 0.019255487969590018
time_window_idx:
  value: 1
