wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: time
leverage:
  value: 15
position_size_pct:
  value: 0.14407974724911904
stop_loss_pct:
  value: 0.01093039786230473
take_profit_pct:
  value: 0.018682401422916713
time_window_idx:
  value: 4
