wandb_version: 1

chunk_size:
  value: 50
chunking_method:
  value: rows
leverage:
  value: 5
position_size_pct:
  value: 0.10850600625649326
stop_loss_pct:
  value: 0.01796912769791246
take_profit_pct:
  value: 0.046475101115612656
time_window_idx:
  value: 5
