wandb_version: 1

chunk_size:
  value: 50
chunking_method:
  value: rows
leverage:
  value: 20
position_size_pct:
  value: 0.12566723895544007
stop_loss_pct:
  value: 0.01445132450095575
take_profit_pct:
  value: 0.06442598809495022
time_window_idx:
  value: 1
