wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: time
leverage:
  value: 5
position_size_pct:
  value: 0.16919051704463975
stop_loss_pct:
  value: 0.011791153711960552
take_profit_pct:
  value: 0.0427505283530661
time_window_idx:
  value: 0
