wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: rows
leverage:
  value: 5
position_size_pct:
  value: 0.1304197405290053
stop_loss_pct:
  value: 0.011789279949789556
take_profit_pct:
  value: 0.07391925859329983
time_window_idx:
  value: 2
