wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: time
leverage:
  value: 10
position_size_pct:
  value: 0.15515739591572164
stop_loss_pct:
  value: 0.0126289709130222
take_profit_pct:
  value: 0.06229877697453995
time_window_idx:
  value: 0
