wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: rows
leverage:
  value: 10
position_size_pct:
  value: 0.11559358293170852
stop_loss_pct:
  value: 0.02288783807719519
take_profit_pct:
  value: 0.05739267045821453
time_window_idx:
  value: 5
