wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: time
leverage:
  value: 5
position_size_pct:
  value: 0.18349004839313848
stop_loss_pct:
  value: 0.01969670824602423
take_profit_pct:
  value: 0.06890677426463603
time_window_idx:
  value: 0
