wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: rows
leverage:
  value: 5
position_size_pct:
  value: 0.0672379349181391
stop_loss_pct:
  value: 0.015282065055975878
take_profit_pct:
  value: 0.0738957833358734
time_window_idx:
  value: 4
