wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: rows
leverage:
  value: 10
position_size_pct:
  value: 0.1061272286767166
stop_loss_pct:
  value: 0.017461609278866228
take_profit_pct:
  value: 0.05607718990514862
time_window_idx:
  value: 4
