wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: time
leverage:
  value: 5
position_size_pct:
  value: 0.1920441501903079
stop_loss_pct:
  value: 0.014163691758160502
take_profit_pct:
  value: 0.05253704748694378
time_window_idx:
  value: 1
