wandb_version: 1

chunk_size:
  value: 100
chunking_method:
  value: rows
leverage:
  value: 15
position_size_pct:
  value: 0.10083719759179906
stop_loss_pct:
  value: 0.013089143263636142
take_profit_pct:
  value: 0.0742336241673019
time_window_idx:
  value: 4
