wandb_version: 1

chunk_size:
  value: 75
chunking_method:
  value: time
leverage:
  value: 15
position_size_pct:
  value: 0.1382575334673935
stop_loss_pct:
  value: 0.016279140786956442
take_profit_pct:
  value: 0.07601642742989319
time_window_idx:
  value: 2
